AE_Projet/Controllers/AdminsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using AE_Projet.Models;
using Microsoft.AspNetCore.Http;

namespace AE_Projet.Controllers
{
    public class AdminsController : Controller
    {
        private readonly ApplicationDbContext _db;

        public AdminsController(ApplicationDbContext db)
        {
            _db = db;
        }
        public async Task<IActionResult> Index(Admin a)
        {
            if (HttpContext.Session.GetString("username") == null || HttpContext.Session.GetString("username") != a.Email_Admin)
            {
                return View("Login");
            }
            
            return View();
        }
        public IActionResult Login()
        {

            return View();
        }

        [ValidateAntiForgeryToken]
        [HttpPost]
        public IActionResult Login(Admin a)
        {
            Admin ad = _db.admins.Where(x => x.Email_Admin == a.Email_Admin && x.Mdp == a.Mdp).SingleOrDefault();
            if (ad!= null)
            {
                HttpContext.Session.SetString("username", a.Email_Admin);
                return View("Index");
            }
            else
            {
                ViewBag.error = "Invalid Account";
                
            }
            return View();
        }

        // GET: Admins
        [HttpGet]
        public IActionResult Logout()
        {
            HttpContext.Session.Remove("username");
            return RedirectToAction("Login");
        }

        // GET: Admins
        public async Task<IActionResult> IndexAdmin(Admin a)
        {
            if (HttpContext.Session.GetString("username") == null /*|| HttpContext.Session.GetString("username") != a.Email_Admin*/)
            {
                return View("Login");
            }
            
            return View(await _db.admins.ToListAsync());
            
        }

        [HttpGet]
        // GET: Admins/Create
        public IActionResult AjouterAdmin(int id,Admin a)
        {
            if (HttpContext.Session.GetString("username") == null /*|| HttpContext.Session.GetString("username") != a.Email_Admin*/)
            {
                return View("Login");
            }
            return View();
        }

        // POST: Admins/Create
        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AjouterAdmin([Bind("Id_Admin,Nom_Admin,Prenom_Admin,CIN_Admin,Email_Admin,Mdp")] Admin admin)
        {
            if (ModelState.IsValid)
            {
                _db.Add(admin);
                await _db.SaveChangesAsync();
                return RedirectToAction("IndexAdmin");
            }
            return View(admin);
        }

        // GET: Admins/Edit/5
        public async Task<IActionResult> ModifierAdmin(int? id,Admin a)
        {
            if (HttpContext.Session.GetString("username") == null /*|| HttpContext.Session.GetString("username") != a.Email_Admin*/)
            {
                return View("Login");
            }

            if (id == null)
            {
                return NotFound();
            }

            var admin = await _db.admins.FindAsync(id);
            if (admin == null)
            {
                return NotFound();
            }
            return View(admin);
        }

        // POST: Admins/Edit/5
       
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> ModifierAdmin(int id, [Bind("Id_Admin,Nom_Admin,Prenom_Admin,CIN_Admin,Email_Admin,Mdp")] Admin admin)
        {
            if (id != admin.Id_Admin)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _db.Update(admin);
                    await _db.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!AdminExists(admin.Id_Admin))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("IndexAdmin");
            }
            return View(admin);
        }

        // GET: Admins/Delete/5
        public async Task<IActionResult> SuppAdmin(int? id,Admin a)
        {
            if (HttpContext.Session.GetString("username") == null /*|| HttpContext.Session.GetString("username") != a.Email_Admin*/)
            {
                return View("Login");
            }
            if (id == null)
            {
                return NotFound();
            }

            var admin = await _db.admins
                .FirstOrDefaultAsync(m => m.Id_Admin == id);
            if (admin == null)
            {
                return NotFound();
            }

            return View(admin);
        }

        // POST: Admins/Delete/5
        [HttpPost, ActionName("SuppAdmin")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> SuppAdminConfirmed(int id)
        {
            var admin = await _db.admins.FindAsync(id);
            _db.admins.Remove(admin);
            await _db.SaveChangesAsync();
            return RedirectToAction("IndexAdmin");
        }

        private bool AdminExists(int id)
        {
            return _db.admins.Any(e => e.Id_Admin == id);
        }
        // GET: Filieres
        public async Task<IActionResult> IndexF(Admin a)
        {
            if (HttpContext.Session.GetString("username") == null)
            {
                return View("Login");
            }
            return View(await _db.filieres.ToListAsync());
        }


        // GET: Filieres/Create
        public IActionResult AjtF(Admin a)
        {
            if (HttpContext.Session.GetString("username") == null /*|| HttpContext.Session.GetString("username") != a.Email_Admin*/)
            {
                return View("Login");
            }
            return View();
        }

        // POST: Filieres/Create
        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AjtF([Bind("Id_Filiere,Nom_Filiere")] Filiere filiere)
        {
            if (ModelState.IsValid)
            {
                _db.Add(filiere);
                await _db.SaveChangesAsync();
                return RedirectToAction("IndexF");
            }
            return View(filiere);
        }

        // GET: Filieres/Edit/5
        public async Task<IActionResult> MdfF(int? id,Admin a)
        {
            if (HttpContext.Session.GetString("username") == null /*|| HttpContext.Session.GetString("username") != a.Email_Admin*/)
            {
                return View("Login");
            }
            if (id == null)
            {
                return NotFound();
            }

            var filiere = await _db.filieres.FindAsync(id);
            if (filiere == null)
            {
                return NotFound();
            }
            return View(filiere);
        }

        // POST: Filieres/Edit/5
        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> MdfF(int id, [Bind("Id_Filiere,Nom_Filiere")] Filiere filiere)
        {
            if (id != filiere.Id_Filiere)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _db.Update(filiere);
                    await _db.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!FiliereExists(filiere.Id_Filiere))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("IndexF");
            }
            return View(filiere);
        }

        // GET: Filieres/Delete/5
        public async Task<IActionResult> SuppF(int? id,Admin a)
        {
            if (HttpContext.Session.GetString("username") == null /*|| HttpContext.Session.GetString("username") != a.Email_Admin*/)
            {
                return View("Login");
            }
            if (id == null)
            {
                return NotFound();
            }

            var filiere = await _db.filieres
                .FirstOrDefaultAsync(m => m.Id_Filiere == id);
            if (filiere == null)
            {
                return NotFound();
            }

            return View(filiere);
        }

        // POST: Filieres/Delete/5
        [HttpPost, ActionName("SuppF")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> SuppFConfirmed(int id)
        {
            var filiere = await _db.filieres.FindAsync(id);
            _db.filieres.Remove(filiere);
            await _db.SaveChangesAsync();
            return RedirectToAction("IndexF");
        }

        private bool FiliereExists(int id)
        {
            return _db.filieres.Any(e => e.Id_Filiere == id);
        }
        // GET: Etudiants
        public async Task<IActionResult> IndexEtd(Admin a)
        {
            if (HttpContext.Session.GetString("username") == null )
            {
                return View("Login");
            }
            var applicationDbContext = _db.etudiants.Include(e => e.filiere);
            return View(await applicationDbContext.ToListAsync());
        }



        // GET: Etudiants/Create
        public IActionResult AjouterEtd(Admin a)
        {
            if (HttpContext.Session.GetString("username") == null || HttpContext.Session.GetString("username") == a.Email_Admin)
            {

AE_Projet/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AE_Projet</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">AE_Projet</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                    @if (User.Identity.IsAuthenticated)
                    {
                        <ul class="nav navbar-nav navbar-right">
                            <li><p class="navbar-text">Hello, @User.Identity.Name</p></li>
                        </ul>
                    }
                    else
                    {
                        <ul class="nav navbar-nav navbar-right">
                            <li><a asp-controller="Account" asp-action="Login">Log in</a></li>
                        </ul>
                    }
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - AE_Projet - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

AE_Projet/Views/Shared/_LayoutAdmin.cshtml
@using Microsoft.AspNetCore.Http;
<!DOCTYPE html>
<html>
<head>
    <title>EMSI</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="~/Content/img/pic.png" rel="shortcut icon" />
    <link href="https://fonts.googleapis.com/css?family=Raleway:400,400i,500,500i,600,600i,700,700i,800,800i" rel="stylesheet">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.13/css/all.css" integrity="sha384-DNOHZ68U8hZfKXOrtjWvjxusGo9WQnrNx2sqG0tfsghAvtVlRW3tvkXWZh58N9jp" crossorigin="anonymous">
    <link rel="stylesheet" href="~/Content/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/Content/css/font-awesome.min.css" />
    <link rel="stylesheet" href="~/Content/css/owl.carousel.css" />
    <link rel="stylesheet" href="~/Content/css/style.css" />
    <style>
        body {
            background-color: #f2f2f2;
        }

        .formulaire {
            margin-top: -60px;
            width: 40%;
            margin-left: 30%;
        }

        #categorie {
            margin-top: 5%;
        }

        .select {
            margin-bottom: 20px;
            width: 100%;
        }
        .last-s {
            margin-left: 25%;
        }

        .site-btn {
            margin-left: -40PX;
        }
        #DG_T {
            float: left;
            width: 50%;
        }

        #DD_T {
            margin-left: 200px;
        }

        #DG {
            float: left;
            width: 50%;
            height: 100px;
        }

        #DD {
            margin-left: 200px;
            height: 100px;
        }
    </style>
</head>
<body>
    <div id="preloder">
        <div class="loader"></div>
    </div>
    <header class="header-section">
        <div class="container">
            <div class="row">
                <div class="col-lg-3 col-md-3">
                    <div class="site-logo">
                        <img src="~/Content/img/logo.png" alt="">
                    </div>

                </div>
                <div class="col-lg-9 col-md-9">
                    <nav class="main-menu">
                        <ul>
                            @*<li><a asp-action="IndexAdmin">Accueil</a></li>*@
                            <li><a href="Profil-admin.html">  <i class="fas fa-user-circle"></i> @Context.Session.GetString("username")</a></li>
                            <a asp-action="logout" class="dex-btn ">Se déconnecter</a>
                        </ul>
                    </nav>
                </div>
            </div>
        </div>
    </header>
    @RenderBody()

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - AE_Projet - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/Content/js/jquery-3.2.1.min.js"></script>
    <script src="~/Content/js/bootstrap.min.js"></script>
    <script src="~/Content/js/mixitup.min.js"></script>
    <script src="~/Content/js/circle-progress.min.js"></script>
    <script src="~/Content/js/owl.carousel.min.js"></script>
    <script src="~/Content/js/main.js"></script>
</body>
</html>

AE_Projet/Views/Shared/_LayoutLoginA.cshtml
<!DOCTYPE html>
<html>
<head>
    <title>EMSI</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="~/Content/img/pic.png" rel="shortcut icon" />
    <link href="https://fonts.googleapis.com/css?family=Raleway:400,400i,500,500i,600,600i,700,700i,800,800i" rel="stylesheet">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.13/css/all.css" integrity="sha384-DNOHZ68U8hZfKXOrtjWvjxusGo9WQnrNx2sqG0tfsghAvtVlRW3tvkXWZh58N9jp" crossorigin="anonymous">
    <link rel="stylesheet" href="~/Content/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/Content/css/font-awesome.min.css" />
    <link rel="stylesheet" href="~/Content/css/owl.carousel.css" />
    <link rel="stylesheet" href="~/Content/css/style.css" />
    <style>
        .formulaire {
            margin-top: -60px;
            width: 40%;
            margin-left: 30%;
        }
        .site-btn {
            margin-left: -40PX;
        }
    </style>
</head>
<body>
    <div id="preloder">
        <div class="loader"></div>
    </div>
    <header class="header-section">
        <div class="container">
            <div class="row">
                <div class="col-lg-3 col-md-3">
                    <div class="site-logo">
                        <img src="~/Content/img/logo.png" alt="">
                    </div>

                </div>
                <div class="col-lg-9 col-md-9">
                    <a asp-controller="Home" asp-action="AjtPre" class="header-btn" style="margin-left:5%">  Accueil</a>
                    <a asp-controller="Professeurs" class="header-btn">  Professeur  </a>
                </div>
            </div>
        </div>
    </header>
    @RenderBody()

    <script src="~/Content/js/jquery-3.2.1.min.js"></script>
    <script src="~/Content/js/bootstrap.min.js"></script>
    <script src="~/Content/js/mixitup.min.js"></script>
    <script src="~/Content/js/circle-progress.min.js"></script>
    <script src="~/Content/js/owl.carousel.min.js"></script>
    <script src="~/Content/js/main.js"></script>
</body>
</html>		

AE_Projet/Views/Shared/_LayoutLoginP.cshtml
<!DOCTYPE html>
<html>
<head>
    <title>EMSI</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="~/Content/img/pic.png" rel="shortcut icon" />
    <link href="https://fonts.googleapis.com/css?family=Raleway:400,400i,500,500i,600,600i,700,700i,800,800i" rel="stylesheet">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.13/css/all.css" integrity="sha384-DNOHZ68U8hZfKXOrtjWvjxusGo9WQnrNx2sqG0tfsghAvtVlRW3tvkXWZh58N9jp" crossorigin="anonymous">
    <link rel="stylesheet" href="~/Content/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/Content/css/font-awesome.min.css" />
    <link rel="stylesheet" href="~/Content/css/owl.carousel.css" />
    <link rel="stylesheet" href="~/Content/css/style.css" />
    <style>
        .formulaire {
            margin-top: -60px;
            width: 40%;
            margin-left: 30%;
        }
        .site-btn {
            margin-left: -40PX;
        }
    </style>
</head>
<body>
    <div id="preloder">
        <div class="loader"></div>
    </div>
    <header class="header-section">
        <div class="container">
            <div class="row">
                <div class="col-lg-3 col-md-3">
                    <div class="site-logo">
                        <img src="~/Content/img/logo.png" alt="">
                    </div>

                </div>
                <div class="col-lg-9 col-md-9">
                    <a asp-controller="Home" asp-action="AjtPre" class="header-btn" style="margin-left:5%">  Accueil</a>
                    <a asp-controller="Admins" class="header-btn">  Admin  </a>
                </div>
            </div>
        </div>
    </header>
    @RenderBody()

    <script src="~/Content/js/jquery-3.2.1.min.js"></script>
    <script src="~/Content/js/bootstrap.min.js"></script>
    <script src="~/Content/js/mixitup.min.js"></script>
    <script src="~/Content/js/circle-progress.min.js"></script>
    <script src="~/Content/js/owl.carousel.min.js"></script>
    <script src="~/Content/js/main.js"></script>
</body>
</html>		

AE_Projet/Views/Shared/_LayoutProf.cshtml
@using Microsoft.AspNetCore.Http;
<!DOCTYPE html>
<html>
<head>
    <title>EMSI</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="~/Content/img/pic.png" rel="shortcut icon" />
    <link href="https://fonts.googleapis.com/css?family=Raleway:400,400i,500,500i,600,600i,700,700i,800,800i" rel="stylesheet">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.13/css/all.css" integrity="sha384-DNOHZ68U8hZfKXOrtjWvjxusGo9WQnrNx2sqG0tfsghAvtVlRW3tvkXWZh58N9jp" crossorigin="anonymous">
    <link rel="stylesheet" href="~/Content/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/Content/css/font-awesome.min.css" />
    <link rel="stylesheet" href="~/Content/css/owl.carousel.css" />
    <link rel="stylesheet" href="~/Content/css/style.css" />
    <style>
        body {
            background-color: #f2f2f2;
        }

        .formulaire {
            margin-top: -60px;
            width: 40%;
            margin-left: 30%;
        }

        #categorie {
            margin-top: 5%;
        }

        select {
            margin-bottom: 20px;
            width: 100%;
        }
        #DG_T {
            float: left;
            width: 50%;
        }

        #DD_T {
            margin-left: 200px;
        }

        #DG {
            float: left;
            width: 50%;
            height: 100px;
        }

        #DD {
            margin-left: 200px;
            height: 100px;
        }
    </style>
</head>
<body>
    <div id="preloder">
        <div class="loader"></div>
    </div>
    <header class="header-section">
        <div class="container">
            <div class="row">
                <div class="col-lg-3 col-md-3">
                    <div class="site-logo">
                        <img src="~/Content/img/logo.png" alt="">
                    </div>

                </div>
                <div class="col-lg-9 col-md-9">
                    <nav class="main-menu">
                        <ul>
                            <li><a asp-action="IndexMat">Accueil</a></li>
                            <li><a href="Profil-admin.html">  <i class="fas fa-user-circle"></i> @Context.Session.GetString("username")</a></li>
                            <a asp-action="logout" class="dex-btn ">Se déconnecter</a>
                        </ul>
                    </nav>
                </div>
            </div>
        </div>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - AE_Projet - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/Content/js/jquery-3.2.1.min.js"></script>
    <script src="~/Content/js/bootstrap.min.js"></script>
    <script src="~/Content/js/mixitup.min.js"></script>
    <script src="~/Content/js/circle-progress.min.js"></script>
    <script src="~/Content/js/owl.carousel.min.js"></script>
    <script src="~/Content/js/main.js"></script>
</body>
</html>